export default {
  Palette: {
    height: "100vh",
    display: "flex",
    flexDirection: "column",
  },
  colors: {
    height: "90%",
  },
  goBack: {
    width: "20%",
    height: "50%",
    display: "inline-block",
    position: "relative",
    margin: "0 auto",
    cursor: "pointer",
    marginBottom: "-4px",
    backgroundColor: "black",
    "& a": {
      position: "absolute",
      top: "50%",
      left: "50%",
      transform: "translate(-50%, -50%)",
      background: "rgba(255, 255, 255, 0.3)",
      color: "white",
      textAlign: "center",
      outline: "none",
      border: "none",
      height: "30px",
      width: "100px",
      lineHeight: "30px",
      textTransform: "uppercase",
      fontSize: "1rem",
      cursor: "pointer",
      textDecoration: "none",
    },
  },
};
